# Generated by Django 2.2 on 2020-10-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('sub_title', models.CharField(blank=True, max_length=350)),
                ('file', models.FileField(upload_to='media/')),
                ('description', models.TextField(blank=True)),
                ('speaker', models.CharField(default='Rev. Sunday James Ekele', max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
