# Generated by Django 2.2 on 2020-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddField(
            model_name='announcements',
            name='annnouncements',
            field=models.ManyToManyField(to='core.Announcement'),
        ),
    ]
