# Generated by Django 2.2 on 2020-10-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Content',
        ),
    ]
